### PR TITLE
Update pom.xml to work with java11

### PR DESCRIPTION
**Pull request by alonsoir**
PR to update Eureka server in order to work with java11.

### CODE REVIEW

**Comment by chuchip** [comment]
Hi, I don't understand it. The program worked  with Java 8. 
You shall  have in mind that the application.properties file is prepared for run in docker. 
If you like to run in local you must change the eureka.client.serviceUrl.defaultZone to localhost.
Thanks for you interest,
Jesús

**Comment by alonsoir** [comment]
Yes, it should work with java8, i offer a pr to work with latest official jdk, java11.
I was trying to get up and running eureka server with jdk10, but it is not longer maintained by Oracle, so i tried with jdk11.

If you don't want to merge, it does not matter. :)

**Comment by alonsoir** [comment]
I will maintain my fork for the future.

**Comment by chuchip** [comment]
Yes, I'm sorry, but I prefer to keep the code with Java 8. Most  people
still use it,

**Pull request closed without merging**
